# Generated by Django 4.2.16 on 2024-11-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
