# Generated by Django 4.2.16 on 2024-11-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_author_alter_book_price_alter_book_title_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='book_media'),
            preserve_default=False,
        ),
    ]
